spring:
  datasource:
    url: jdbc:h2:./data/eatgo;DB_CLOSE_ON_EXIT=FALSE;AUTO_SERVER=TRUE
  jpa:
    hibernate:
      ddl-auto: update

jwt :
  scret : 12345678901234567890123456789000
---

spring:
  profiles: test
  datasource:
    url: jdbc:h2:mem:test
