spring:
  datasource:
    url: jdbc:h2:./data/eatgo;DB_CLOSE_ON_EXIT=FALSE;AUTO_SERVER=TRUE
  jpa:
    hibernate:
      ddl-auto: update
---

spring:
  profiles: test
  datasource:
    url: jdbc:h2:mem:test

---
spring:
  profiles: mysql
  datasource:
    url : jdbc:mysql://${MYSQL_HOST}:3360/${MYSQL_DATABASE}
    username : ${MYSQL_USER}
    password : ${MYSQL_PASSWORD}